#!/bin/bash
#sysinfo - A script to produce a system information HTML file


##### Constants

TITLE= "System Information for $HOSTNAME"
RIGHT_NOW=$(date + "%x %r %Z")
TIME_STAMP="Updated on $RIGHT_NOW by $USER"


##### Functions

system_info()
{
  echo "<h2>System release info</h2>"
  echo "<p>Function not yet implemented</p>"
}

show_uptime()
{
  echo "<h2>System uptime</h2>"
  echo "<pre>"
  uptime
  echo "</pre>"
}

drive_space()
{
  echo "<h2>Filesystem space</h2>"
  echo "<pre>"
  df -h
  echo "</pre>"
}


home_space()
{
   #Must be Superuser
  if [ "$(id -u)" = "0"; then
    echo "<h2>Home directory space by user</h2>"
    echo "<pre>"
    echo "Bytes Directory"
      du -sh /usr/local/google/home/* | sort -nr
    echo "</pre>"
  fi
}

write_page()
{
    cat <<- _EOF_
    <html>
        <head>
            <title> $title </title>
        </head>

    <body>
	<h1>$title</h1>
        <p>$TIME_STAMP</p>
        $(system_info)
        $(show_uptime)
        $(drive_space)
        $(home_space)
    </body>
    </html>
_EOF_
}

###### Main


interactive=
filename=~/sysinfo_page.html

while [ "$1" != "" ]; do
  case $1 in
    -f | --file )       shift
                        filename=$1
                        ;;
    -i | interactive )  interactive=1
                        ;;
    -h | --help )       usage
                        exit 1
  esac
  shift
done
# Test to verify cli processing

if [ "$interactive" = "1" ]; then
    echo "interactive is on"
else
      echo "interactive is off"
    fi
    echo "output file = $filename"

#Write Page

# write_page > $filename
